@startuml
left to right direction

:Cliente : as c

usecase "Meter dinero" as UC1
usecase "Pedir Azucar" as UC2
usecase "Pedir producto" as UC3
usecase "Cancelar" as UC4
usecase "Devolver dinero" as UC5

c -- UC1
c -- UC2
c -- UC3
c -- UC4
UC3 ..> UC5 : <<Incluide>>
UC4 ..> UC5 : <<Incluide>>
@enduml